import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  loader: {
    ".tsx": "tsx",
    ".ts": "ts",
  },
});

if (prod) {
  await context.rebuild();
  bundleCss();
  process.exit(0);
} else {
  bundleCss();
  await context.watch();
}

/**
 * Obsidian loads styles from styles.css in the plugin folder.
 * Combine Excalidraw's upstream CSS with our plugin CSS into a single output.
 */
function bundleCss() {
  const excalidrawCss = readFileSync(
    resolve(__dirname, "node_modules/@excalidraw/excalidraw/dist/prod/index.css"),
    "utf-8",
  );
  const pluginCss = readFileSync(resolve(__dirname, "src/styles.css"), "utf-8");
  writeFileSync(
    resolve(__dirname, "styles.css"),
    `/* === Excalidraw upstream styles (do not edit) === */\n${excalidrawCss}\n\n/* === Plugin styles === */\n${pluginCss}`,
  );
}
